package com.example.registry.web.dto

enum class ErrorCode(val value: String) {
    VALIDATION_ERROR("VALIDATION_ERROR"),
    NOT_FOUND("NOT_FOUND"),
    UNAUTHORIZED("UNAUTHORIZED"),
    FORBIDDEN("FORBIDDEN"),
    CONFLICT("CONFLICT"),
    INTERNAL_ERROR("INTERNAL_ERROR"),
    IDEMPOTENCY_KEY_REQUIRED("IDEMPOTENCY_KEY_REQUIRED"),
    TENANT_NOT_FOUND("TENANT_NOT_FOUND"),
    INVALID_TENANT("INVALID_TENANT")
}

