package com.example.registry.config

import org.springframework.boot.context.event.ApplicationReadyEvent
import org.springframework.context.ApplicationListener
import org.springframework.context.annotation.Profile
import org.springframework.stereotype.Component
import javax.sql.DataSource
import java.sql.Connection

/**
 * Creates database schema manually for H2 tests using native SQL.
 * This bypasses Hibernate's DDL generation which has issues with TIMESTAMP(0).
 */
@Component
@Profile("test")
class H2SchemaCreator(private val dataSource: DataSource) : ApplicationListener<ApplicationReadyEvent> {
    
    private var schemaCreated = false
    
    override fun onApplicationEvent(event: ApplicationReadyEvent) {
        if (!schemaCreated) {
            createSchema()
            schemaCreated = true
        }
    }
    
    fun createSchema() {
        dataSource.connection.use { conn ->
            conn.autoCommit = false
            try {
                // Create tables in dependency order
                createTenantsTable(conn)
                createPermissionsTable(conn)
                createRolePermissionsTable(conn)
                createAppUsersTable(conn)
                createMembershipsTable(conn)
                createTenantRolePermissionsTable(conn)
                createPersonsTable(conn)
                createSacramentEventsTable(conn)
                createCertificatesTable(conn)
                createContentBlocksTable(conn)
                createAuditLogsTable(conn)
                createIdempotencyKeysTable(conn)
                createOutboxTable(conn)
                
                conn.commit()
            } catch (e: Exception) {
                conn.rollback()
                throw e
            }
        }
    }
    
    private fun createTenantsTable(conn: Connection) {
        conn.createStatement().execute("""
            CREATE TABLE IF NOT EXISTS "tenants" (
                "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "slug" VARCHAR(100) NOT NULL UNIQUE,
                "name" VARCHAR(200) NOT NULL,
                "parent_id" BIGINT,
                "theme" JSON,
                "created_at" TIMESTAMP NOT NULL
            )
        """.trimIndent())
    }
    
    private fun createPermissionsTable(conn: Connection) {
        conn.createStatement().execute("""
            CREATE TABLE IF NOT EXISTS "permissions" (
                "key" VARCHAR(100) PRIMARY KEY,
                "category" VARCHAR(50),
                "description" VARCHAR(500),
                "parent_key" VARCHAR(100)
            )
        """.trimIndent())
    }
    
    private fun createRolePermissionsTable(conn: Connection) {
        conn.createStatement().execute("""
            CREATE TABLE IF NOT EXISTS "role_permissions" (
                "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "role" VARCHAR(50) NOT NULL,
                "permission_key" VARCHAR(100) NOT NULL,
                UNIQUE ("role", "permission_key"),
                FOREIGN KEY ("permission_key") REFERENCES "permissions"("key")
            )
        """.trimIndent())
        try {
            conn.createStatement().execute("CREATE INDEX IF NOT EXISTS idx_role_permissions_role ON \"role_permissions\"(\"role\")")
        } catch (e: Exception) {
            // Index might already exist
        }
    }
    
    private fun createAppUsersTable(conn: Connection) {
        conn.createStatement().execute("""
            CREATE TABLE IF NOT EXISTS "app_users" (
                "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "email" VARCHAR(255) NOT NULL UNIQUE,
                "full_name" VARCHAR(200) NOT NULL,
                "mfa_enabled" BOOLEAN NOT NULL DEFAULT FALSE,
                "status" VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
                "created_at" TIMESTAMP NOT NULL
            )
        """.trimIndent())
        // Create indexes
        try {
            conn.createStatement().execute("CREATE INDEX IF NOT EXISTS idx_app_users_email ON \"app_users\"(\"email\")")
            conn.createStatement().execute("CREATE INDEX IF NOT EXISTS idx_app_users_status ON \"app_users\"(\"status\")")
        } catch (e: Exception) {
            // Indexes might already exist
        }
    }
    
    private fun createMembershipsTable(conn: Connection) {
        conn.createStatement().execute("""
            CREATE TABLE IF NOT EXISTS "memberships" (
                "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "user_id" BIGINT NOT NULL,
                "tenant_id" BIGINT NOT NULL,
                "role" VARCHAR(50) NOT NULL,
                "status" VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
                "granted_by" BIGINT,
                "granted_at" TIMESTAMP NOT NULL,
                "expires_at" TIMESTAMP,
                UNIQUE ("user_id", "tenant_id"),
                FOREIGN KEY ("user_id") REFERENCES "app_users"("id"),
                FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id")
            )
        """.trimIndent())
        // Create indexes
        try {
            conn.createStatement().execute("CREATE INDEX IF NOT EXISTS idx_memberships_user_id ON \"memberships\"(\"user_id\")")
            conn.createStatement().execute("CREATE INDEX IF NOT EXISTS idx_memberships_tenant_id ON \"memberships\"(\"tenant_id\")")
            conn.createStatement().execute("CREATE INDEX IF NOT EXISTS idx_memberships_role ON \"memberships\"(\"role\")")
            conn.createStatement().execute("CREATE INDEX IF NOT EXISTS idx_memberships_status ON \"memberships\"(\"status\")")
            conn.createStatement().execute("CREATE INDEX IF NOT EXISTS idx_memberships_user_tenant_status ON \"memberships\"(\"user_id\", \"tenant_id\", \"status\")")
        } catch (e: Exception) {
            // Indexes might already exist
        }
    }
    
    private fun createPersonsTable(conn: Connection) {
        conn.createStatement().execute("""
            CREATE TABLE IF NOT EXISTS "persons" (
                "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "uuid" UUID NOT NULL UNIQUE,
                "tenant_id" BIGINT NOT NULL,
                "first_name" VARCHAR(100) NOT NULL,
                "last_name" VARCHAR(100) NOT NULL,
                "middle_name" VARCHAR(100),
                "date_of_birth" DATE,
                "gender" VARCHAR(20),
                "baptism_name" VARCHAR(100),
                "father_name" VARCHAR(200),
                "mother_name" VARCHAR(200),
                "created_at" TIMESTAMP NOT NULL,
                "updated_at" TIMESTAMP,
                FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id")
            )
        """.trimIndent())
    }
    
    private fun createTenantRolePermissionsTable(conn: Connection) {
        conn.createStatement().execute("""
            CREATE TABLE IF NOT EXISTS "tenant_role_permissions" (
                "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "tenant_id" BIGINT NOT NULL,
                "role" VARCHAR(50) NOT NULL,
                "permission_key" VARCHAR(100) NOT NULL,
                "granted" BOOLEAN NOT NULL DEFAULT TRUE,
                UNIQUE ("tenant_id", "role", "permission_key"),
                FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id")
            )
        """.trimIndent())
        // Create indexes
        try {
            conn.createStatement().execute("CREATE INDEX IF NOT EXISTS idx_tenant_role_permissions_tenant_id ON \"tenant_role_permissions\"(\"tenant_id\")")
            conn.createStatement().execute("CREATE INDEX IF NOT EXISTS idx_tenant_role_permissions_role ON \"tenant_role_permissions\"(\"role\")")
            conn.createStatement().execute("CREATE INDEX IF NOT EXISTS idx_tenant_role_permissions_tenant_role ON \"tenant_role_permissions\"(\"tenant_id\", \"role\")")
        } catch (e: Exception) {
            // Indexes might already exist
        }
    }
    
    private fun createSacramentEventsTable(conn: Connection) {
        conn.createStatement().execute("""
            CREATE TABLE IF NOT EXISTS "sacrament_events" (
                "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "tenant_id" BIGINT NOT NULL,
                "type" VARCHAR(50) NOT NULL,
                "person_id" UUID NOT NULL,
                "date" DATE NOT NULL,
                "priest_name" VARCHAR(200) NOT NULL,
                "book_no" INTEGER NOT NULL,
                "page_no" INTEGER NOT NULL,
                "entry_no" INTEGER NOT NULL,
                "status" VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
                "created_by" BIGINT NOT NULL,
                "created_at" TIMESTAMP NOT NULL,
                "updated_by" BIGINT,
                "updated_at" TIMESTAMP,
                "deactivated_at" TIMESTAMP,
                "deactivated_by" BIGINT,
                "deactivation_reason" VARCHAR(500),
                "metadata" JSON,
                FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id")
            )
        """.trimIndent())
    }
    
    private fun createCertificatesTable(conn: Connection) {
        conn.createStatement().execute("""
            CREATE TABLE IF NOT EXISTS "certificates" (
                "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "event_id" BIGINT NOT NULL,
                "serial_no" VARCHAR(26) NOT NULL UNIQUE,
                "issued_at" TIMESTAMP NOT NULL,
                "issuer_id" BIGINT NOT NULL,
                "revocation_status" VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
                FOREIGN KEY ("event_id") REFERENCES "sacrament_events"("id")
            )
        """.trimIndent())
        // Create indexes
        try {
            conn.createStatement().execute("CREATE INDEX IF NOT EXISTS idx_certificates_event ON \"certificates\"(\"event_id\")")
            conn.createStatement().execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_certificates_serial ON \"certificates\"(\"serial_no\")")
        } catch (e: Exception) {
            // Indexes might already exist
        }
    }
    
    private fun createContentBlocksTable(conn: Connection) {
        conn.createStatement().execute("""
            CREATE TABLE IF NOT EXISTS "content_blocks" (
                "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "tenant_id" BIGINT NOT NULL,
                "key" VARCHAR(100) NOT NULL,
                "draft" JSON,
                "published" JSON,
                "updated_at" TIMESTAMP NOT NULL,
                UNIQUE ("tenant_id", "key"),
                FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id")
            )
        """.trimIndent())
        // Create indexes
        try {
            conn.createStatement().execute("CREATE INDEX IF NOT EXISTS idx_content_blocks_tenant ON \"content_blocks\"(\"tenant_id\")")
        } catch (e: Exception) {
            // Index might already exist
        }
    }
    
    private fun createAuditLogsTable(conn: Connection) {
        conn.createStatement().execute("""
            CREATE TABLE IF NOT EXISTS "audit_logs" (
                "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "tenant_id" BIGINT,
                "actor_id" BIGINT,
                "action" VARCHAR(50) NOT NULL,
                "entity" VARCHAR(100) NOT NULL,
                "entity_id" VARCHAR(50),
                "before" JSON,
                "after" JSON,
                "ts" TIMESTAMP NOT NULL,
                "hash" VARCHAR(64),
                "prev_hash" VARCHAR(64)
            )
        """.trimIndent())
    }
    
    private fun createIdempotencyKeysTable(conn: Connection) {
        conn.createStatement().execute("""
            CREATE TABLE IF NOT EXISTS "idempotency_keys" (
                "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "tenant_id" BIGINT NOT NULL,
                "key" VARCHAR(255) NOT NULL,
                "request_hash" VARCHAR(64),
                "response_code" INTEGER,
                "created_at" TIMESTAMP NOT NULL,
                UNIQUE ("tenant_id", "key"),
                FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id")
            )
        """.trimIndent())
    }
    
    private fun createOutboxTable(conn: Connection) {
        conn.createStatement().execute("""
            CREATE TABLE IF NOT EXISTS "outbox" (
                "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "tenant_id" BIGINT,
                "topic" VARCHAR(100) NOT NULL,
                "payload" TEXT NOT NULL,
                "status" VARCHAR(50) NOT NULL DEFAULT 'PENDING',
                "created_at" TIMESTAMP NOT NULL,
                "published_at" TIMESTAMP,
                "retry_count" INTEGER NOT NULL DEFAULT 0,
                "error_message" VARCHAR(1000)
            )
        """.trimIndent())
    }
}

